### ISSUE TITLE
findOTB() on Linux still will return "FALSE"

### ISSUE THREAD

**Issue by aloboa** [r-spatial/link2GI#18]
Apparently the fix does not work in case OTB is not under /usr, even if specifying searchLocation
`findOTB(searchLocation = "/home/alobo/OTB-6.6.0-Linux64", quiet = FALSE)`
results in FALSE

Note that the currentely advised installation is through a binary package i.e.  OTB-6.6.1-Linux64.run
that can be deployed in your home directory.

**Comment by gisma** [comment]
@aloboa sorry for the delay. I think it is fixed now. Additionally I have changed the default searchpath to home. Please try and test the master branch.

**Comment by aloboa** [comment]
If I download from
https://github.com/r-spatial/link2GI
and try to install it in R (on my Debian machine) I get:
```
> install.packages("~/Documents/link2GI-master.zip", repos = NULL, type = "win.binary")
Installing package into ‘/home/alobo/R/x86_64-pc-linux-gnu-library/3.5’
(as ‘lib’ is unspecified)
Error in install.packages : cannot install Windows binary packages on this platform
```
If I use `devtools::install_github("r-spatial/link2GI")
`
I get link2GI_0.3-5 and, with it, I still have the same problem:
```
> findOTB(searchLocation = "/home/alobo/OTB-6.6.0-Linux64/")
[1] FALSE
```
I can try this afternoon on windows.

**Comment by aloboa** [comment]
Curiously, it does work on windows using the zip downloaded from the code page:
https://github.com/r-spatial/link2GI/archive/master.zip

```
> findOTB()
                                           binDir                                  baseDir
1               C:\\ALOBO\\OTB-6.6.0-Win64\\bin\\               C:\\ALOBO\\OTB-6.6.0-Win64
2 C:\\QGIS_RemoteSensing_64bits\\QGIS\\OTB\\bin\\ C:\\QGIS_RemoteSensing_64bits\\QGIS\\OTB
  installation_type
1               OTB
2           qgisOTB
```

**Comment by gisma** [comment]
Hm strange,  I am am developing under Linux and I have checked it under Linux. What happens if you use 
`devtools::install_github("gisma/link2GI", ref = "master")` instead of downloading the zip file?

If downloading the zip file you may try also:
`devtools::install_local("~/Downloads/link2GI-master.zip")`

**Comment by aloboa** [comment]
I did use`devtools::install_github("r-spatial/link2GI") ` also (see above), but I note you mention using ` gisma/link2GI`  
I'll try again tomorrow (unless the weather lets me go the field, then it would be after-tomorrow).

**Comment by aloboa** [comment]
On linux, after installing with `devtools::install_github("gisma/link2GI", ref = "master")`

```
> require(link2GI)
Loading required package: link2GI
> findOTB()
[1] FALSE
> findOTB("/home/alobo/OTB-6.6.0-Linux64")
                              binDir                                   otbCmd
1 /home/alobo/OTB-6.6.0-Linux64/bin/ /home/alobo/OTB-6.6.0-Linux64/bin/otbcli
> linkOTB()
$exist
[1] FALSE
> linkOTB(bin_OTB="/home/alobo/OTB-6.6.0-Linux64/bin")
$exist
[1] FALSE
> linkOTB(root_OTB="/home/alobo/OTB-6.6.0-Linux64")
$exist
[1] FALSE
> linkOTB(searchLocation ="/home/alobo/OTB-6.6.0-Linux64")
$pathOTB
                              binDir
1 /home/alobo/OTB-6.6.0-Linux64/bin/

$version
                              binDir                                   otbCmd
1 /home/alobo/OTB-6.6.0-Linux64/bin/ /home/alobo/OTB-6.6.0-Linux64/bin/otbcli

$exist
[1] TRUE
> otb <- linkOTB(searchLocation ="/home/alobo/OTB-6.6.0-Linux64")
> algo <- parseOTBAlgorithms(gili=otb)
> algo[27]
[1] "DomainTransform"
> algo_keyword<- "EdgeExtraction"
> otb_algorithm<-algo[algo[]==algo_keyword]
> otb_algorithm
[1] "EdgeExtraction"
> algo_cmd <-parseOTBFunction(algo = otb_algorithm,gili = otb)
Error in sapply(args, "[", 2)[[1]] : subscript out of bounds

```

**Comment by gisma** [comment]
Thanks for testing it. Now I've got an idea whats going wrong. I will fix it and push it asap. Please use then again the regular r-spatial github for installing.
`devtools::install_github("r-spatial/link2GI")`

**Comment by aloboa** [comment]
After new installation, still some problem with parseOTBFunction()
Also, finfOTB(), without any clue, takes too long. Perhaps better advice the user to provide an insight
on the searchLocation

```
> findOTB()
                                binDir                                     otbCmd
1   /home/alobo/OTB-6.6.0-Linux64/bin/   /home/alobo/OTB-6.6.0-Linux64/bin/otbcli
2 /home/alobo/OTBMercurial/OTBbin/bin/ /home/alobo/OTBMercurial/OTBbin/bin/otbcli
3   /home/alobo/OTB-6.6.1-Linux64/bin/   /home/alobo/OTB-6.6.1-Linux64/bin/otbcli
> otb <- linkOTB(searchLocation ="/home/alobo/OTB-6.6.0-Linux64")
> algo <- parseOTBAlgorithms(gili=otb)
> algo[27]
[1] "DomainTransform"
> algo_keyword<- "EdgeExtraction"
> otb_algorithm<-algo[algo[]==algo_keyword]
> otb_algorithm
[1] "EdgeExtraction"
> algo_cmd <-parseOTBFunction(algo = otb_algorithm,gili = otb)
Error in sapply(args, "[", 2)[[1]] : subscript out of bounds
```

**Comment by gisma** [comment]
Well it is a brute force recursive search. If it is done under windows  and if you have a huge hard drive it is a nightmare. Running Linux it is much faster. I tried to  expressed this in the vignette that if you know what and how  to link it is much better to drill down there. However it is a question of balance what users know about their installations.... Maybe I should address that once scanned it would be helpful to save the retrieved list for further use. The fastest way is the one you have mentioned the most comfortable way would be something like:
`otb <- linkOTB(ver_select = 1)`. However in this case the algorithm is perfoming a recursive search at the home directory. 
I tried to fix the error. It is depending on the new format of how OTB now generates the HTML help pages. This has been different under Linux and obviously this is not the case anymore.

**Comment by aloboa** [comment]
Works fine on Debian, I'll test on windows later.
Thanks!
```
> require(link2GI)
> otb <- linkOTB(searchLocation ="/home/alobo/OTB-6.6.0-Linux64")
> algo_keyword<- "EdgeExtraction"
> otb_algorithm<-algo[algo[]==algo_keyword]
> otb_algorithm
[1] "EdgeExtraction"
> algo_cmd <-parseOTBFunction(algo = otb_algorithm,gili = otb)
> algo_cmd
$`-in`
[1] "mandatory"

$`-channel`
[1] "1"

$`-ram`
[1] "128"

$`-filter`
[1] "gradient"

$`-filter.touzi.xradius`
[1] "1"

$`-filter.touzi.yradius`
[1] "1"

$`-out`
[1] "float"

$`-progress`
[1] "false"

```

**Comment by aloboa** [comment]
Works on windows as well but note some minor problems:

```
> require(link2GI)
> otb <- linkOTB(searchLocation ="C:/ALOBO/OTB-6.6.0-Win64/bin")
Error in data.frame(binDir = root_dir, baseDir = installDir, installation_type = installerType,  : 
  object 'root_dir' not found
> otb <- linkOTB(searchLocation ="C:\\ALOBO\\OTB-6.6.0-Win64\\bin")
> algo <- parseOTBAlgorithms(gili=otb)
> algo_keyword<- "EdgeExtraction"
> otb_algorithm<-algo[algo[]==algo_keyword]
> otb_algorithm
character(0)
> algo_keyword<- "EdgeExtraction.bat"
> otb_algorithm<-algo[algo[]==algo_keyword]
> otb_algorithm
[1] "EdgeExtraction.bat"
> algo_cmd <-parseOTBFunction(algo = otb_algorithm,gili = otb)
> algo_cmd
$`-in`
[1] "mandatory"

$`-channel`
[1] "1"

$`-ram`
[1] "128"

$`-filter`
[1] "gradient"

$`-filter.touzi.xradius`
[1] "1"

$`-filter.touzi.yradius`
[1] "1"

$`-out`
[1] "float"

$`-progress`
[1] "false"
```

**Comment by gisma** [comment]
Due to the fact that the search command is a windows system command I had (if user provided as in your case) to switch slashes back into backslashes again.

**Comment by aloboa** [comment]
Perhaps you can consider using shell() on windows:
 `It will also help with related issues such as having to switch out every / for \.`
https://stackoverflow.com/questions/41807060/difference-between-system-and-shell

**Comment by gisma** [comment]
@aloboa  hope it works for the moment?

Thanks for the hint. I have used this quite often due to the fact that I am dealing massively (unlike most of the R folks) with system calls and piping pragmatically all kind of executable code.  In this case it is only a dirty preliminary hack because all kind of path notations that windows like to produce have to be checked and converted. Unfortunately  `shell` is not tackling down this problems because the old  `shell` call deals in a very specific way with different calls depending on the involved `cmd.exe`. Because I do not check an register what kind of Windows version the user is running I want to use the more stable system call and check the string by myself.  Hoever IMHO there is no clean real cross platform solution with the usual R tools at all dealing with this topic at all - but I would be happy to learn that I am wrong. 

I think one of the most promising approaches is the `fs` package.  I am currently integrating it in all my related packages to get rid of this tinkering around and up to now it seems to work from DOS, Windows and Unix dialects....

**Comment by aloboa** [comment]
> @aloboa hope it works for the moment?

Yes it does, just using the "//" whenever on windows. 

Great to know that the fs package can make all these issues more OS-independent.

**Comment by gisma** [comment]
Is it ok for you  to close the issue?

**Comment by aloboa** [comment]
Yes, sure.
Thanks
